In [ ]:
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
file = 'drive/MyDrive/TechChallenge/cmsc154.html'

Mounted at /content/drive

In [ ]:
HTMLFile = open(file, "r")
contents = HTMLFile.read()
bsText = BeautifulSoup(contents, 'html')

In [ ]:
soup = BeautifulSoup(HTMLFile, "html.parser")
html_text = soup.get_text()
f = open("html_text.txt", "w")         # Creating html_text.txt File
for line in html_text:
	f.write(line)
f.close()

In [ ]:
# "what are the most important things you learned" responses
c = []
table1 = bsText.find("table")#, {"title":"TheTitle"} )
for row in table1.findAll("tr"):
    c.append(row.text[1:-1])
important = pd.DataFrame(c, columns=['comment'])
important

                                              comment
0                                            Comments
1   I learned good time management skills, as ther...
2   Bit ManipulationReading assembly languageUnder...
3   How computers are organized, architecture, sof...
4   Computer Architecture, Operating Systems, Asse...
5   Bits, understanding assembly code, understandi...
6            Think more about memory usageStart early
7   Bit manipulation, assembly code, cache registe...
8   Bit manipulation in C, assembly, hardware conf...
9   We learned a lot about the computer architectu...
10             Bits,Assembly,Cache, operating systems
11  > A lot of C coding> Fundamentals of OS> Proce...
12           assembly language, bit manip, OS, caches
13  understanding Assembly code, caches, processes...
14  Working with bits, bytes, reading assembly cod...
15  To start early on the projects. I feel as if I...
16     Bit operation & Assembly Language & Cache & OS
17  Assembly language, computer architecture, memo...
18                                     I have no idea
19  How to debug code with gdb, that assignment ga...
20  Operating systems, memory, machine code, bit m...
21                                      Cache and OS.

In [ ]:
# "what contributed" responses
c = []
table2 = bsText.findAll('table')[1]
for row in table2.findAll("tr"):
    c.append(row.text[1:-1])
contri = pd.DataFrame(c, columns=['comment'])
contri

                                              comment
0                                            Comments
1   The textbooks helped to make the lectures more...
2   The projects were great at making sure you act...
3   We had lectures, labs, projects, hw, and exams...
4                        The powerpoints were clutch.
5   homework and projects contributed to my learni...
6                        lectures and all assignments
7   Lectures and textbook were really helpful, and...
8   Lectures were a great help in understanding th...
9   The lectures were very thorough. The projects,...
10  Lectures and homeworks were good for conceptua...
11  Lecture was the most helpful, Prof Lu explaine...
12                     lectures were the most helpful
13  The lectures were the most important and the e...
14  The lectures were the main way to learn. Homew...
15  The projects are a real hands–on medium of app...
16  Projects are extremely helpful for understandi...
17  Prof. Lu's lectures were good and informative,...
18  I will have left this course feeling like I le...
19  the projects were amazing ways to put things w...
20  Professor Lu's lectures were absolutely fantas...
21  Lectures and the homework assignments contribu...
22                    The lectures were very helpful.

In [ ]:
# "please respond to the following" responses
row_names = []
mean = []
median = []
strongly_disagree = []
disagree = []
neutral = []
agree = []
strongly_agree = []

table3 = bsText.findAll('table')[2]
table_body = table3.find('tbody')

for h in table_body.find_all('th'):
  row_names.append(h.text)

for tr in table_body.find_all('tr'):
  td = tr.find_all('td')
  mean.append(td[0].text)
  median.append(td[1].text)
  strongly_disagree.append(td[2].text)
  disagree.append(td[3].text)
  neutral.append(td[4].text)
  agree.append(td[5].text)
  strongly_agree.append(td[6].text)

dict_eval = {'name': row_names, 'mean': mean, 'median': median, 'strongly_disagree': strongly_disagree, 'disagree': disagree, 'neutral': neutral, 'agree': agree, 'strongly_agree': strongly_agree}
eval = pd.DataFrame(dict_eval)
eval

,name,mean,median,strongly_disagree,disagree,neutral,agree,strongly_agree
0,This course challenged me intellectually.,4.74,5.00,0.00%,0.00%,0.00%,26.09%,73.91%
1,I understood the purpose of this course and wh...,4.26,4.00,4.35%,0.00%,4.35%,47.83%,43.48%
2,I understood the standards for success on assi...,4.65,5.00,0.00%,0.00%,4.35%,26.09%,69.57%
3,Class time enhanced my ability to succeed in g...,4.39,5.00,0.00%,8.70%,4.35%,26.09%,60.87%
4,I received feedback on my performance that hel...,4.04,4.00,0.00%,4.35%,30.43%,21.74%,43.48%
5,My work was evaluated fairly.,4.65,5.00,0.00%,0.00%,4.35%,26.09%,69.57%
6,I felt respected in this class.,4.70,5.00,0.00%,0.00%,8.70%,13.04%,78.26%
7,"Overall, this was an excellent course.",4.41,5.00,4.55%,0.00%,9.09%,22.73%,63.64%

In [ ]:
# "additional comments" responses
c = []
table3 = bsText.findAll('table')[3]
for row in table3.findAll("tr"):
    c.append(row.text[1:-1])
additional = pd.DataFrame(c, columns=['comment'])
additional

                                             comment
0                                           Comments
1  I enjoyed the fact that most of the projects w...
2  The projects use auto–grader, so as long as yo...
3      Great professor, so sweet and a good lecturer
4  The professor is very understanding of the dif...
5  I really enjoyed this course and liked doing t...
6  cs 154 is notoriously hard, but SHAN LU is so ...
7  I appreciated that we were allowed a partner f...
8  I'm so jealous of future cs students who get t...

Analysis

In [ ]:
pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 7.5 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from vaderSentiment) (2.23.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->vaderSentiment) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->vaderSentiment) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->vaderSentiment) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->vaderSentiment) (2021.10.8)
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
import string
import re
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
# CONTENT
stopwords = nltk.corpus.stopwords.words('english')
# remove stopwords
important['stopwords_removed'] = important['comment'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stopwords)]))
# remove punctuations
important["clean_comment"] = important['stopwords_removed'].apply(lambda x: re.sub('[^A-Za-z0-9]', ' ', x))

pd.DataFrame(pd.Series(' '.join(important['clean_comment']).lower().split()).value_counts()[:10])

                0
assembly       11
code            7
systems         7
bit             6
memory          6
operating       6
os              5
cache           5
computer        4
understanding   4

In [ ]:
# Sentiment Analysis on "what contributed most" and "additional comments"
all_comments = pd.concat([contri, additional], axis=0)

# remove stopwords
stopwords = nltk.corpus.stopwords.words('english')
all_comments['stopwords_removed'] = all_comments['comment'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stopwords)]))

analyzer = SentimentIntensityAnalyzer()
scores = pd.DataFrame(all_comments['stopwords_removed'].map(lambda x: analyzer.polarity_scores(x)))

total_neg = 0
total_neu = 0
total_pos = 0
for i in range(0, len(scores) - 1):
  list_score = re.findall(r"\d+\.\d+", str(scores.iloc[i]))
  total_neg += float(list_score[0])
  total_neu += float(list_score[1])
  total_pos += float(list_score[2])
avg_neg = total_neg / len(scores)
avg_neu = total_neu / len(scores)
avg_pos = total_pos / len(scores)
[avg_neg, avg_neu, avg_pos]

[0.034437499999999996, 0.6616875000000001, 0.2725937500000001]